version: '3'
services:
  front-end:
    image: tinsae/waa-final-project-front-end:1.0.1
    ports:
      - "3000:3000"
    depends_on:
      - back-end
    tty: true
    stdin_open: true
    environment:
      - VITE_BASE_URL=http://localhost:8080


  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - CLOUD_AWS_CREDENTIALS_ACCESS_KEY={$CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      - CLOUD_AWS_CREDENTIALS_SECRET_KEY={$CLOUD_AWS_CREDENTIALS_SECRET_KEY}

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    #    ports:
    #      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local